name: Fights
run-name: Fights

on:
  schedule:
     - cron: "*/20 1-23 * * *"
  workflow_dispatch:

jobs:
  FightsForAllAccounts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Fights"
        run: |
          touch .env
          echo "LOGIN_BORSUK=${{ secrets.LOGIN_BORSUK }}" >> .env
          echo "LOGIN_LYYSYY=${{ secrets.LOGIN_VEGETA }}" >> .env
          echo "LOGIN_VEGETA=${{ secrets.LOGIN_LYYSYY }}" >> .env
          echo "PASSWORD_BORSUK=${{ secrets.PASSWORD_BORSUK }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD_LYYSYY_VEGETA }}" >> .env
          cat .env
          npx playwright install chromium
          npm run chromeTest
    